/* This file was generated by syncqt. */
#ifndef QT_QTVERSIT_VERSION_H
#define QT_QTVERSIT_VERSION_H

#define QTVERSIT_VERSION_STR "0.0.0"

#define QTVERSIT_VERSION 0x000000

#endif // QT_QTVERSIT_VERSION_H
